// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddForward(config: $models.ForwardConfig): $CancellablePromise<string> {
    return $Call.ByID(4132582929, config);
}

export function AddJumpHost(config: $models.JumpHostConfig): $CancellablePromise<string> {
    return $Call.ByID(3121460106, config);
}

export function DeleteForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(2424831583, id);
}

export function DeleteJumpHost(id: string): $CancellablePromise<void> {
    return $Call.ByID(3540441188, id);
}

export function ExportConfig(password: string): $CancellablePromise<void> {
    return $Call.ByID(2222068969, password);
}

export function GetForwards(): $CancellablePromise<$models.ForwardConfig[]> {
    return $Call.ByID(2892671581).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetJumpHosts(): $CancellablePromise<$models.JumpHostConfig[]> {
    return $Call.ByID(3360602722).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetLogs(forwardID: string): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(1743981476, forwardID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ImportConfig(password: string): $CancellablePromise<void> {
    return $Call.ByID(3706958138, password);
}

/**
 * Start is called when the application starts
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1627660663);
}

export function StartForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(1030754052, id);
}

export function StopForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(3463127858, id);
}

export function UpdateForward(config: $models.ForwardConfig): $CancellablePromise<void> {
    return $Call.ByID(514439393, config);
}

export function UpdateJumpHost(config: $models.JumpHostConfig): $CancellablePromise<void> {
    return $Call.ByID(3966924378, config);
}

// Private type creation functions
const $$createType0 = $models.ForwardConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.JumpHostConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.LogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
