// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddForward(config: $models.ForwardConfig): $CancellablePromise<string> {
    return $Call.ByID(4132582929, config);
}

export function AddGroup(name: string): $CancellablePromise<string> {
    return $Call.ByID(3799890143, name);
}

export function AddJumpHost(config: $models.JumpHostConfig): $CancellablePromise<string> {
    return $Call.ByID(3121460106, config);
}

export function BatchUpdateGroup(forwardIDs: string[], groupID: string): $CancellablePromise<void> {
    return $Call.ByID(2172071189, forwardIDs, groupID);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(2675659504).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(2424831583, id);
}

export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(3779215765, id);
}

export function DeleteJumpHost(id: string): $CancellablePromise<void> {
    return $Call.ByID(3540441188, id);
}

export function ExportConfig(password: string): $CancellablePromise<void> {
    return $Call.ByID(2222068969, password);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1780012486);
}

export function GetForwards(): $CancellablePromise<$models.ForwardConfig[]> {
    return $Call.ByID(2892671581).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetGroups(): $CancellablePromise<$models.Group[]> {
    return $Call.ByID(2476446367).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetJumpHosts(): $CancellablePromise<$models.JumpHostConfig[]> {
    return $Call.ByID(3360602722).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetLogs(forwardID: string): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(1743981476, forwardID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ImportConfig(password: string): $CancellablePromise<void> {
    return $Call.ByID(3706958138, password);
}

export function PerformUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1736600371);
}

export function PerformUpdateWithLogs(): $CancellablePromise<void> {
    return $Call.ByID(423979656);
}

/**
 * Start is called when the application starts
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1627660663);
}

export function StartForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(1030754052, id);
}

export function StopForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(3463127858, id);
}

export function UpdateForward(config: $models.ForwardConfig): $CancellablePromise<void> {
    return $Call.ByID(514439393, config);
}

export function UpdateGroup(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3141499567, id, name);
}

export function UpdateJumpHost(config: $models.JumpHostConfig): $CancellablePromise<void> {
    return $Call.ByID(3966924378, config);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ForwardConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Group.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.JumpHostConfig.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.LogEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
