// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectionInfo {
    "id": string;
    "srcAddr": string;
    "startTime": number;

    /** Creates a new ConnectionInfo instance. */
    constructor($$source: Partial<ConnectionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("srcAddr" in $$source)) {
            this["srcAddr"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo($$parsedSource as Partial<ConnectionInfo>);
    }
}

export class ForwardConfig {
    "id": string;
    "name": string;

    /**
     * ID of the group it belongs to
     */
    "groupId": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "jumpHostId": string;

    /**
     * "running", "stopped", "error"
     */
    "status": string;

    /**
     * Current active connections
     */
    "connections": ConnectionInfo[];

    /** Creates a new ForwardConfig instance. */
    constructor($$source: Partial<ForwardConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteHost" in $$source)) {
            this["remoteHost"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("jumpHostId" in $$source)) {
            this["jumpHostId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("connections" in $$source)) {
            this["connections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ForwardConfig {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField8_0($$parsedSource["connections"]);
        }
        return new ForwardConfig($$parsedSource as Partial<ForwardConfig>);
    }
}

export class Group {
    "id": string;
    "name": string;

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group($$parsedSource as Partial<Group>);
    }
}

export class JumpHostConfig {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "user": string;

    /**
     * "password", "key"
     */
    "authType": string;
    "password": string;
    "keyPath": string;

    /** Creates a new JumpHostConfig instance. */
    constructor($$source: Partial<JumpHostConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("authType" in $$source)) {
            this["authType"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("keyPath" in $$source)) {
            this["keyPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JumpHostConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): JumpHostConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JumpHostConfig($$parsedSource as Partial<JumpHostConfig>);
    }
}

export class LogEntry {
    "timestamp": number;
    "message": string;

    /**
     * "info", "error"
     */
    "level": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class UpdateInfo {
    "latestVersion": string;
    "currentVersion": string;
    "hasUpdate": boolean;
    "releaseUrl": string;
    "releaseNotes": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = ConnectionInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
